version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: phishing_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: phishing
